Repository MhL5/Meta-Blog, pull requests merged in 2024-05, with the labels that each got.

#7 Auth
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/controllers/authController.ts
  backend/src/controllers/globalErrorController/globalErrorController.ts
  backend/src/devData/importDevData.ts
  backend/src/devData/userData.json
  backend/src/model/userModel.ts
  backend/src/routes/userRouter.ts
  backend/src/templates/welcome.html
  backend/src/utils/email.ts
  backend/src/utils/env.ts
  backend/src/utils/generateHashedToken.ts
  backend/todo.md
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/Logo.tsx
  frontend/src/components/ui/Spinner.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/components/ui/toaster.tsx
  frontend/src/components/ui/use-toast.ts
  frontend/src/features/authentication/AuthContext.tsx
  frontend/src/features/authentication/LoginForm.tsx
  frontend/src/features/authentication/SignUpForm.tsx
  frontend/src/features/authentication/SignUpTab.tsx
  frontend/src/features/authentication/useSignUp.ts
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/providers/Providers.tsx
  frontend/src/router/Router.tsx
  frontend/src/services/axiosApi.ts
Labels: enhancement

#10 Auth
  backend/.vscode/settings.json
  backend/example.config.env
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/connectDB.ts
  backend/src/controllers/authControllers/authController.ts
  backend/src/controllers/authControllers/handlers/login.ts
  backend/src/controllers/authControllers/handlers/logout.ts
  backend/src/controllers/authControllers/handlers/refreshToken.ts
  backend/src/controllers/authControllers/handlers/singUp.ts
  backend/src/controllers/authControllers/handlers/verifyEmail.ts
  backend/src/controllers/authControllers/logoutController.ts
  backend/src/controllers/authControllers/refreshTokenController.ts
  backend/src/controllers/authControllers/utils/authUtils.ts
  backend/src/controllers/authControllers/utils/generateAuthTokens.ts
  backend/src/controllers/globalErrorController/globalErrorController.ts
  backend/src/controllers/handlerFactory.ts
  backend/src/middlewares/verifyJWT.ts
  backend/src/model/articleViewModel.ts
  backend/src/model/userModel.ts
  backend/src/routes/userRouter.ts
  backend/src/server.ts
  backend/src/utils/appError.ts
  backend/src/utils/catchAsync.ts
  backend/src/utils/deepCloneObj.ts
  backend/src/utils/email.ts
  backend/src/utils/env.ts
  backend/src/utils/generateHashedToken.ts
Labels: enhancement

#12 Auth
  backend/src/app.ts
  backend/src/middlewares/verifyJWTAccessToken.ts
  frontend/src/features/authentication/AuthContext.tsx
  frontend/src/features/authentication/services/logoutApi.ts
  frontend/src/features/authentication/services/refreshApi.ts
  frontend/src/features/authentication/services/signUpApi.ts
  frontend/src/features/authentication/useAxiosPrivate.ts
  frontend/src/features/authentication/useLogout.tsx
  frontend/src/features/authentication/useRefreshToken.ts
  frontend/src/features/authentication/useSignUp.ts
Labels: bug, enhancement

#13 Auth update
  backend/example.config.env
  backend/src/app.ts
  backend/src/controllers/authControllers/handlers/login.ts
  backend/src/controllers/authControllers/handlers/singUp.ts
  backend/src/controllers/authControllers/utils/authUtils.ts
  backend/src/controllers/globalErrorController/errorHandlers.ts
  backend/src/controllers/globalErrorController/globalErrorController.ts
  backend/src/middlewares/protect.ts
  backend/src/middlewares/verifyJWTAccessToken.ts
  backend/src/model/userModel.ts
Labels: documentation, enhancement

#14 Auth
  backend/src/middlewares/rateLimiter.ts
  backend/src/routes/userRouter.ts
  frontend/src/components/layout/Header.tsx
  frontend/src/features/authentication/AuthContext.tsx
  frontend/src/features/authentication/useLogin.ts
Labels: enhancement

#17 Frontend UI
  backend/src/controllers/articleController.ts
  backend/src/controllers/handlerFactory.ts
  backend/src/devData/articleData.json
  backend/src/devData/importDevData.ts
  backend/src/devData/userData.json
  backend/src/model/articleCommentModel.ts
  backend/src/model/articleModel.ts
  frontend/src/components/ArticleCard.tsx
  frontend/src/components/FeaturedPosts.tsx
  frontend/src/components/ui/UserDropDown.tsx
  frontend/src/features/authentication/useLogin.ts
  frontend/src/hooks/useGetArticles.tsx
  frontend/src/pages/ArticlePage.tsx
  frontend/src/pages/Homepage.tsx
  frontend/src/router/Router.tsx
Labels: enhancement
